### ISSUE TITLE
Add the functionality of "Available" action

### ISSUE THREAD

**Issue by ZzSteven-Wang** [CSCI-GA-2820-FA23-001/products#28]
**As a** [role]
**I need** [function]  
**So that** [benefit]  
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by wenbo-bao** [comment]
duplicate issue
