### ISSUE TITLE
Need the Ability to Delete a Product

### ISSUE THREAD

**Issue by ZzSteven-Wang** [CSCI-GA-2820-FA23-001/products#3]
**As a** Product Operator
**I need** a way to delete a product
**So that** it no longer shows up in the list of products
   
 ### Details and Assumptions
 * The unique id of the product to be deleted should be pass in by the user
 * A call to `GET /products` should list all products
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that the product id `123` exists
 When I issue `GET /products`
I should see the product with id `123` in the list of products
When I issue `DELETE /prodocts/123`
 Then the product with id `123` should be deleted
 When I issue `GET /products`
I should not see the product with id `123` in the list of products
```

**Comment by tokotority** [comment]
sorry but I think the role of deleting products should better belong to the products manager, not user.

**Comment by ZzSteven-Wang** [comment]
> sorry but I think the role of deleting products should better belong to the products manager, not user.

Yes, you are right. By "user" I meant product manager. I'll change it to avoid confusion.
