### ISSUE TITLE
Create the Database Model

### ISSUE THREAD

**Issue by ZzSteven-Wang** [CSCI-GA-2820-FA23-001/products#4]
**As a** Developer
**I need** to create the database model
**So that** we can use to store data
   
 ### Details and Assumptions
 * The database model must have below attributes
    * ID (unique, perhaps a SKU - Stock Keeping Unit)
    * Name
    * Description
    * Price
    * Available (True, False)
    * Image_url
    * Category
    * ~~Create_time~~
    * ~~Update_time~~

   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the database model is created
 When we perform any operation of data record.
 Then they should all follow the model
```

**Comment by haofrank** [comment]
We can add Create_time and Update_time later, because these should be automatically maintained by the database.
