### ISSUE TITLE
Implement Product Categories

### ISSUE THREAD

**Issue by luoyantao99** [CSCI-GA-2820-FA23-001/products#8]
**As** a products operator,
**I need** to implement product categories in the "products" service,
**So that** we can categorize products for easier navigation.
### Assumptions:
- Product model and database table are already defined.
### Acceptance Criteria:
```gherkin
Given the existence of the product model and database table,
When a new product is created,
Then there should be an option to assign the product to a specific category.
```

**Comment by haofrank** [comment]
I added this field to the data record, and created, read, and updated all operations on this field. This has been implemented in previous PR.
